var a = 2;
a = a - 1;
a++;
var b = 8;
b += 2;
var c = a + b * b;
console.log("===>" + 102);
console.log(c);
var d = a * b + b;
console.log("===>" + 30);
console.log(d);
var e = a * (b + b);
console.log("===>" + 40);
console.log(e);
var f = a * b / a;
console.log("===>" + 10);
console.log(f);
var g = b / a * a;
console.log("===>" + 10);
console.log(g);